import type { TradeRecord } from "@/types/trading";

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

/**
 * Export trade history as CSV file.
 */
export function exportTradeHistoryCSV(trades: TradeRecord[]) {
  const headers = [
    "Date",
    "Ticker",
    "Side",
    "Quantity",
    "Price",
    "P&L",
    "Fees",
    "Slippage",
    "Notes",
  ];

  const rows = trades.map((t) => [
    new Date(t.simulationDate).toISOString().split("T")[0],
    t.ticker,
    t.side,
    t.quantity.toString(),
    t.price.toFixed(2),
    t.realizedPnL.toFixed(2),
    t.fees.toFixed(2),
    t.slippage.toFixed(4),
    (t.notes ?? "").replace(/,/g, ";"),
  ]);

  const csv = [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");
  downloadFile(csv, `alpha-deck-trades-${Date.now()}.csv`, "text/csv");
}

/**
 * Export a text-based portfolio report.
 */
export function exportPortfolioReport(stats: {
  level: number;
  title: string;
  xp: number;
  portfolioValue: number;
  totalPnL: number;
  totalTrades: number;
  profitableTrades: number;
  winRate: string;
  achievements: number;
  largestWin: number;
  consecutiveWins: number;
}) {
  const lines = [
    "═══════════════════════════════════════",
    "       ALPHA DECK — Portfolio Report",
    "═══════════════════════════════════════",
    "",
    `Date:              ${new Date().toLocaleDateString()}`,
    `Level:             ${stats.level} (${stats.title})`,
    `XP:                ${stats.xp}`,
    "",
    "─── Performance ───────────────────────",
    `Portfolio Value:    $${stats.portfolioValue.toLocaleString("en-US", { minimumFractionDigits: 2 })}`,
    `Total P&L:         $${stats.totalPnL.toLocaleString("en-US", { minimumFractionDigits: 2 })}`,
    `Total Trades:      ${stats.totalTrades}`,
    `Profitable Trades: ${stats.profitableTrades}`,
    `Win Rate:          ${stats.winRate}%`,
    `Largest Win:       $${stats.largestWin.toLocaleString("en-US", { minimumFractionDigits: 2 })}`,
    `Best Streak:       ${stats.consecutiveWins} consecutive wins`,
    "",
    "─── Achievements ──────────────────────",
    `Unlocked:          ${stats.achievements}`,
    "",
    "═══════════════════════════════════════",
    "  Generated by Alpha Deck Trading Sim",
    "═══════════════════════════════════════",
  ];

  downloadFile(lines.join("\n"), `alpha-deck-report-${Date.now()}.txt`, "text/plain");
}

/**
 * Generate shareable text summary for clipboard.
 */
export function generateShareText(stats: {
  level: number;
  title: string;
  portfolioValue: number;
  totalPnL: number;
  winRate: string;
  totalTrades: number;
  achievements: number;
}): string {
  const pnlSign = stats.totalPnL >= 0 ? "+" : "";
  return [
    `🎮 Alpha Deck Trading Sim`,
    `📊 Lv.${stats.level} ${stats.title}`,
    `💰 Portfolio: $${stats.portfolioValue.toLocaleString("en-US", { minimumFractionDigits: 2 })}`,
    `📈 P&L: ${pnlSign}$${stats.totalPnL.toLocaleString("en-US", { minimumFractionDigits: 2 })}`,
    `🎯 Win Rate: ${stats.winRate}% (${stats.totalTrades} trades)`,
    `🏆 ${stats.achievements} achievements unlocked`,
  ].join("\n");
}
